# Generated by Django 5.2.7 on 2025-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoperfil',
            name='foto',
            field=models.ImageField(default='fotos_perfil/not_user.jpg', upload_to='fotos_perfil/'),
        ),
    ]
