# Generated by Django 5.2.7 on 2025-11-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('codigo_analise', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome_analise', models.CharField(max_length=150)),
                ('tipo_analise', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('codigo_propriedade', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nome_propriedade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='usuarios.usuarioprodutor')),
            ],
            options={
                'db_table': 'propriedade',
            },
        ),
        migrations.CreateModel(
            name='AnalisesPropriedade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_realizacao', models.DateField()),
                ('resultado', models.CharField(max_length=255)),
                ('codigo_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='analises.analise')),
                ('codigo_propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='analises.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('codigo_talhao', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cultura', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_solo', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('codigo_propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='analises.propriedade')),
            ],
            options={
                'db_table': 'talhao',
            },
        ),
        migrations.CreateModel(
            name='AnaliseTalhao',
            fields=[
                ('id_analise', models.AutoField(primary_key=True, serialize=False)),
                ('laboratorio_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('acidez', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calcio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('magnesio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('potassio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fosforo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('enxofre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ferro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('manganes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('zinco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cobre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('boro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('aluminio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('codigo_talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='analises.talhao')),
            ],
            options={
                'db_table': 'analise_talhao',
            },
        ),
    ]
